[theme]
# Starbucks color palette
primaryColor = "#00704A"  # Starbucks green
backgroundColor = "#1E1E1E"  # Dark background for dark mode
secondaryBackgroundColor = "#2D2D2D"  # Slightly lighter dark background
textColor = "#FFFFFF"  # White text for dark mode
font = "sans serif"

# Dark mode alternative theme (light mode)
[theme.light]
primaryColor = "#00704A"  # Starbucks green
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray
textColor = "#262730"  # Dark text

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false 